FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY assets/ /usr/share/nginx/html/assets/
COPY projects/ /usr/share/nginx/html/projects/
COPY es/ /usr/share/nginx/html/es/
COPY en/ /usr/share/nginx/html/en/
COPY pt/ /usr/share/nginx/html/pt/

EXPOSE 80
