export const PROJECTS = [
  {
    slug: 'portfolio-release-platform',
    title: 'Portfolio Release Platform',
    subtitle: 'GitHub -> CI/CD -> Docker -> Terraform -> cloud hosting',
    category: 'Current project',
    rarity: 'legendary',
    tint: 'violet',
    iconName: 'pipeline',
    oneLiner: 'The release pipeline this site ships through.',
    impact: 'A static platform validated by CI, Docker build, smoke test with readiness retries, and infrastructure validation. Free-tier guardrailed by design: no Kubernetes, no managed database, no large instances, no auto-deploy without approval.',
    stack: ['Docker', 'Nginx', 'CI/CD', 'Terraform', 'Static hosting'],
    status: 'Live - multilingual EN/ES/PT',
    repoUrl: 'https://github.com/leop27',
  },
  {
    slug: 'api-platform',
    title: 'API Platform Modernization',
    subtitle: 'API platform · ownership mapping · onboarding',
    category: 'Work front · 01',
    rarity: 'epic',
    tint: 'violet',
    iconName: 'gateway',
    oneLiner: 'One shared platform becoming clearer, safer, team-owned pieces.',
    impact: 'Runbook written, onboarding defined, tracking in place. Current priority is explicit: close one or two complete splits in a production-like environment. Scope discipline is release discipline.',
    stack: ['API platform', 'Runbooks', 'Team onboarding'],
    status: 'Platform coordination - production-like validation',
  },
  {
    slug: 'cloud-infrastructure',
    title: 'Cloud Infrastructure Mapping',
    subtitle: 'Container services · release workflow · traffic routing',
    category: 'Work front · 02',
    rarity: 'epic',
    tint: 'crimson',
    iconName: 'loadbalancer',
    oneLiner: 'Turning tribal knowledge into clear operational documentation.',
    impact: 'Container services, image registry, routing and release workflow details translated into operational documentation the whole team can use.',
    stack: ['Container services', 'Image registry', 'Traffic routing', 'Runbooks'],
    status: 'Deep work - knowledge transfer',
  },
  {
    slug: 'enterprise-migration',
    title: 'Enterprise Migration',
    subtitle: 'Cross-team traceability',
    category: 'Work front · 03',
    rarity: 'epic',
    tint: 'plum',
    iconName: 'branch',
    oneLiner: 'Visibility is the antidote to migration friction.',
    impact: 'Coordinating migrations from legacy platforms to modern collaboration tooling: governance alignment, access management, onboarding and migration tracking across multiple engineering teams.',
    stack: ['Enterprise tooling', 'Identity workflows', 'Access management', 'Git'],
    status: 'Cross-team coordination - ongoing',
  },
  {
    slug: 'ai-automation-workspace',
    title: 'AI Automation Workspace',
    subtitle: 'Agents · docs systems · delivery loops',
    category: 'Automation lab',
    rarity: 'epic',
    tint: 'graphite',
    iconName: 'gear',
    oneLiner: 'AI-assisted engineering with clear process boundaries.',
    impact: 'A practical lab for AI-assisted workflows applied to documentation systems, repetitive operations and personal delivery loops. Automation that reduces friction without hiding context.',
    stack: ['AI agents', 'Documentation', 'Automation'],
    status: 'Active lab',
  },
  {
    slug: 'next-objective',
    title: 'Next objective',
    subtitle: 'Roadmap · declared',
    category: "What's next",
    rarity: 'rare',
    tint: 'violet',
    iconName: 'arrow',
    oneLiner: 'The platform is live; next comes the personal content layer.',
    impact: 'Declared milestones, not promises: publish the first restoration log, build a dedicated DevOps Lab page for technical writeups, and add a project timeline connecting releases, repairs and learning notes.',
    stack: ['Content layer', 'Restoration log', 'Writeups'],
    status: 'Declared - in design',
  },
];

export const RARITY_LABEL = {
  legendary: 'Legendary',
  epic: 'Epic',
  rare: 'Rare',
};
